/**
 * Market tiles: 1024×1024 images generated by the app.
 *
 * Each category gets its own mark, drawn as geometry rather than a letter. A
 * letterform would need a font file and a rasteriser, and at 48px in the room a
 * single capital is much less distinguishable than a shape. These read at both
 * sizes — a 48px thumbnail in a phone list and a full-bleed 1024px card on a
 * projector — which is the only size range that actually matters.
 *
 * The palette is one accent per category over a near-black base. Not decorative:
 * the market card is the densest thing in a watch-party room, and a colourful
 * tile behind a title competes with the price, which is the one number the
 * room exists to move.
 */

import { Canvas, type Rgb } from './png'

export interface TileSpec {
  /** Panta category. Doubles as the tile's cache key. */
  category: string
  accent: Rgb
  /** Which mark to draw. See `drawMark`. */
  mark: 'bars' | 'arcs' | 'grid' | 'wedge' | 'cross' | 'ring' | 'steps' | 'burst'
}

const BASE: Rgb = [14, 15, 18]

/** Kept in step with `PANTA_CATEGORIES` in lib/panta/types.ts. */
export const TILE_SPECS: readonly TileSpec[] = [
  { category: 'sports', accent: [122, 201, 128], mark: 'arcs' },
  { category: 'crypto', accent: [139, 124, 246], mark: 'steps' },
  { category: 'politics', accent: [232, 160, 92], mark: 'bars' },
  { category: 'entertainment', accent: [232, 106, 148], mark: 'burst' },
  { category: 'finance', accent: [86, 178, 214], mark: 'grid' },
  { category: 'science', accent: [120, 196, 214], mark: 'ring' },
  { category: 'world', accent: [168, 178, 190], mark: 'wedge' },
  { category: 'other', accent: [142, 146, 158], mark: 'cross' },
]

/**
 * The tile for a category, or the neutral one.
 *
 * Falls back rather than throwing, because Panta fetches this URL from its own
 * infrastructure and a missing tile is a failed market creation the user has
 * already paid to quote. `FALLBACK` is the last element rather than a separate
 * constant so it cannot drift out of the list it belongs to.
 */
const FALLBACK: TileSpec = TILE_SPECS[TILE_SPECS.length - 1] ?? {
  category: 'other',
  accent: [142, 146, 158],
  mark: 'cross',
}

export function tileFor(category: string): TileSpec {
  return TILE_SPECS.find((t) => t.category === category) ?? FALLBACK
}

/**
 * The absolute URL to hand Panta as a market's `imageUrl`.
 *
 * Panta fetches this from its own servers, so it has to be absolute and public
 * — which means it is built from the ORIGIN the browser is currently on. That
 * has one hard consequence: this is only correct once the app is deployed. On
 * localhost it produces `http://localhost:3000/tiles/…`, which Panta cannot
 * reach and the create will be rejected. There is no way to detect that from
 * here without a config flag, so the caller passes the origin in rather than
 * reading `location` here, and the sheet is responsible for not offering a
 * create it knows will fail.
 *
 * The path shape is asserted against the route in scripts/verify-resilience.ts.
 * The two drifting apart is not a hypothetical: an earlier version served
 * `/tiles/[category]` while the natural guess was `/tiles/crypto.png`, and every
 * such request rendered the neutral tile with a 200 and no error.
 */
export function tileUrl(origin: string, category: string): string {
  return `${origin.replace(/\/+$/, '')}/tiles/${encodeURIComponent(category)}.png`
}

/**
 * Paint one tile.
 *
 * Antialiasing is a 2×2 coverage sample rather than a real edge filter. It
 * triples the paint cost — still a few milliseconds for 1024² — and turns every
 * hard edge from a staircase into something that looks deliberate on a
 * projector. Doing it properly would need distance fields; for flat geometric
 * marks, supersampling IS the distance field.
 */
export function paintTile(spec: TileSpec, size: number): Canvas {
  const canvas = new Canvas(size)
  const centre = size / 2

  canvas.fill((x, y) => {
    // A shallow diagonal gradient plus a corner vignette. Both exist to stop
    // the tile reading as a flat swatch at 1024px; at 48px both are invisible,
    // which is fine, because the mark is doing the work at that size.
    const diagonal = (x / size) * 0.5 + (y / size) * 0.5
    const dx = (x - centre) / centre
    const dy = (y - centre) / centre
    const vignette = Math.min(1, Math.sqrt(dx * dx + dy * dy) * 0.55)

    let colour = Canvas.mix(Canvas.shade(spec.accent, 0.88), BASE, diagonal * 0.5)
    colour = Canvas.mix(colour, BASE, vignette)

    if (insideMark(spec.mark, x + 0.25, y + 0.25, size) || insideMark(spec.mark, x + 0.75, y + 0.75, size)) {
      colour = Canvas.mix(colour, spec.accent, 0.9)
    }
    return colour
  })

  return canvas
}

/** True when (x, y) in pixel space falls inside the mark. */
function insideMark(mark: TileSpec['mark'], x: number, y: number, size: number): boolean {
  const c = size / 2
  const r = size * 0.28
  const nx = (x - c) / r
  const ny = (y - c) / r
  const d = Math.sqrt(nx * nx + ny * ny)

  switch (mark) {
    // Three horizontal bars of decreasing width. Reads as a bar chart, which is
    // the most literal thing a "politics" tile can be without a flag.
    //
    // `half` is a magnitude, not a signed offset. An early version wrote these
    // as negative numbers on the assumption they were x-coordinates, which made
    // every test `|nx| < negative` and rendered the mark invisible: 0% of the
    // canvas. A shape that is entirely absent is indistinguishable from a shape
    // that is merely faint, which is why this is now covered by a coverage
    // assertion rather than left to review.
    case 'bars': {
      const bands: ReadonlyArray<readonly [top: number, half: number, height: number]> = [
        [-0.72, 0.62, 0.32],
        [-0.16, 0.4, 0.32],
        [0.4, 0.18, 0.32],
      ]
      return bands.some(([top, half, height]) => ny > top && ny < top + height && Math.abs(nx) < half)
    }

    // Concentric arcs, open at the bottom. A radar sweep; unmistakably a live
    // in-progress thing, which is the entire premise of the product.
    case 'arcs': {
      if (ny > 0.45) return false
      const radii = [0.45, 0.72, 1.0]
      return radii.some((radius, i) => {
        const band = i === 0 ? 0.14 : 0.12
        return d > radius - band && d < radius
      })
    }

    // A grid of squares with a diagonal of filled cells. A ledger.
    case 'grid': {
      const cell = 0.34
      const gx = Math.floor((nx + 1.2) / cell)
      const gy = Math.floor((ny + 1.2) / cell)
      if (gx < 0 || gy < 0 || gx > 6 || gy > 6) return false
      if ((nx + 1.2) % cell > 0.82 || (ny + 1.2) % cell > 0.82) return false
      return gx === gy || (gx + gy) % 5 === 0
    }

    // A single rising wedge. The most abstract of the set, and the reason "world"
    // is not a globe: a sphere at 48px is a dot, and a dot is not a tile.
    case 'wedge': {
      return ny > -0.9 && ny < 0.9 && nx > -0.9 && nx < ny * 0.9 + 0.1
    }

    // A ring with a gap, plus a dot in the gap. An eye, or an aperture.
    case 'ring': {
      if (d > 0.98 && d < 1.12) {
        const angle = Math.atan2(ny, nx)
        return angle < -0.5 || angle > 1.9
      }
      return d < 0.22
    }

    // Staircase blocks climbing to the upper right. Works because a market price
    // moving up is the one chart everyone recognises.
    //
    // The bands are 0.45 wide and 0.44 tall because at 48px the original thinner
    // version measured 4.3% coverage — the lowest of the eight, and close enough
    // to the politics tile that the two were the hardest pair to tell apart. The
    // shape is unchanged; it is just big enough to survive the downscale.
    case 'steps': {
      const band = 0.45
      const level = Math.floor((nx + 0.9) / band)
      if (level < 0 || level >= 4) return false
      const top = 0.88 - level * 0.47
      return ny > top - 0.44 && ny < top
    }

    // Radiating spokes. Loud, which is right for entertainment.
    case 'burst': {
      if (d > 1.05 || d < 0.28) return false
      const angle = Math.atan2(ny, nx)
      return Math.abs(Math.sin(angle * 4)) > 0.55
    }

    // A plus. The fallback, and deliberately the plainest of the eight.
    case 'cross': {
      return (Math.abs(nx) < 0.2 && Math.abs(ny) < 0.95) || (Math.abs(ny) < 0.2 && Math.abs(nx) < 0.95)
    }
  }
}
