import { db, type Db } from '@/lib/db'
import type { QueryResultRow } from 'pg'

/**
 * `session_events` — the append-only ledger.
 *
 * ⚠ INSERT ONLY. There is deliberately no update function and no delete
 * function in this module, and there should never be one. The scoreboard and
 * the activity feed are derived from this table, so a corrected event is a new
 * event, not an edited one. If a bug corrupts a row, the fix is a migration or
 * a compensating event — never a mutation. This is the shape event sourcing would
 * give us, at Postgres cost and without a second database (ARCHITECTURE.md §4.5).
 */

export type SessionEventType =
  | 'session.started'
  | 'market.created'
  | 'market.registered'
  | 'trade.reported'
  | 'claim.reported'
  | 'market.resolved'
  | 'session.ended'

export interface SessionEventRow extends QueryResultRow {
  id: string
  session_id: string
  type: SessionEventType
  actor_user_id: string | null
  market_id: string | null
  payload: Record<string, unknown>
  created_at: Date
}

export interface SessionEvent {
  id: string
  sessionId: string
  type: SessionEventType
  actorUserId: string | null
  marketId: string | null
  payload: Record<string, unknown>
  createdAt: Date
}

/**
 * Payload for a reported trade.
 *
 * These exact keys are read by `v_scoreboard` in SQL. The shape is duplicated
 * here rather than imported from the view because the view casts to NUMERIC with
 * a regex guard: a malformed field yields NULL instead of aborting the query.
 * The types keep the write side honest; the view keeps the read side safe.
 *
 *   side        'yes' | 'no'
 *   amountUsdc  decimal string, what the user paid
 *   shares      decimal string, position size in shares
 */
export interface TradeEventPayload {
  side: 'yes' | 'no'
  amountUsdc: string
  shares: string
  signature?: string
}

export interface ClaimEventPayload {
  signature?: string
  /** What was claimed, in USDC, as a decimal string. */
  amountUsdc?: string
}

export interface MarketEventPayload {
  pantaMarketId?: string
  imageUrl?: string
  yesPrice?: string
  noPrice?: string
  outcome?: 'yes' | 'no'
}

function toEvent(row: SessionEventRow): SessionEvent {
  return {
    id: String(row.id),
    sessionId: row.session_id,
    type: row.type,
    actorUserId: row.actor_user_id,
    marketId: row.market_id,
    // JSONB always comes back parsed, but a null would break every consumer.
    payload: row.payload ?? {},
    createdAt: row.created_at,
  }
}

/**
 * Append an event.
 *
 * `id` is returned rather than generated by the caller: it is a BIGSERIAL, and
 * its monotonic ordering is what makes the timeline and the market/trade
 * correlation reliable even when two events land inside the same millisecond.
 */
export async function appendEvent(
  event: {
    sessionId: string
    type: SessionEventType
    actorUserId?: string | null
    marketId?: string | null
    payload?: Record<string, unknown>
  },
  executor: Db = db,
): Promise<SessionEvent> {
  const row = await executor.queryOne<SessionEventRow>(
    `INSERT INTO session_events (session_id, type, actor_user_id, market_id, payload)
     VALUES ($1, $2, $3, $4, $5::jsonb)
     RETURNING id, session_id, type, actor_user_id, market_id, payload, created_at`,
    [
      event.sessionId,
      event.type,
      event.actorUserId ?? null,
      event.marketId ?? null,
      JSON.stringify(event.payload ?? {}),
    ],
  )
  if (!row) throw new Error('event insert returned no row')
  return toEvent(row)
}

/**
 * Append several events atomically.
 *
 * Used where one user action is several facts — registering a market emits both
 * `market.registered` and a price snapshot event. A crash between them would
 * leave the timeline claiming something that did not finish.
 */
export async function appendEvents(
  events: Array<{
    sessionId: string
    type: SessionEventType
    actorUserId?: string | null
    marketId?: string | null
    payload?: Record<string, unknown>
  }>,
  executor: Db = db,
): Promise<SessionEvent[]> {
  if (events.length === 0) return []

  const values: string[] = []
  const params: unknown[] = []
  for (const [index, event] of events.entries()) {
    const base = index * 5
    values.push(`($${base + 1}, $${base + 2}, $${base + 3}, $${base + 4}, $${base + 5}::jsonb)`)
    params.push(
      event.sessionId,
      event.type,
      event.actorUserId ?? null,
      event.marketId ?? null,
      JSON.stringify(event.payload ?? {}),
    )
  }

  const rows = await executor.query<SessionEventRow>(
    `INSERT INTO session_events (session_id, type, actor_user_id, market_id, payload)
     VALUES ${values.join(', ')}
     RETURNING id, session_id, type, actor_user_id, market_id, payload, created_at`,
    params,
  )
  return rows.map(toEvent)
}

export interface TimelineFilters {
  /** Only these event types. Omit for all. */
  types?: SessionEventType[]
  /** Return events strictly after this id, for polling without gaps. */
  afterId?: string
  limit?: number
}

/**
 * Read the session timeline, newest first.
 *
 * Polling uses `afterId` rather than a timestamp. Two events can share a
 * millisecond, and a timestamp cursor would silently skip one of them — which on
 * a trade tape means a trade that never appears in the room.
 */
export async function listEvents(
  sessionId: string,
  filters: TimelineFilters = {},
  executor: Db = db,
): Promise<SessionEvent[]> {
  const limit = Math.min(Math.max(filters.limit ?? 50, 1), 200)
  const params: unknown[] = [sessionId]
  let sql = `SELECT id, session_id, type, actor_user_id, market_id, payload, created_at
               FROM session_events
              WHERE session_id = $1`

  if (filters.types && filters.types.length > 0) {
    params.push(filters.types)
    sql += ` AND type = ANY($${params.length}::text[])`
  }
  if (filters.afterId) {
    params.push(filters.afterId)
    sql += ` AND id < $${params.length}::bigint`
  }

  params.push(limit)
  sql += ` ORDER BY id DESC LIMIT $${params.length}`

  const rows = await executor.query<SessionEventRow>(sql, params)
  return rows.map(toEvent)
}

/** Count events of a type in a session. Used by the ops checks. */
export async function countEvents(
  sessionId: string,
  type: SessionEventType,
  executor: Db = db,
): Promise<number> {
  const row = await executor.queryOne<{ count: string }>(
    `SELECT count(*)::text AS count
       FROM session_events
      WHERE session_id = $1 AND type = $2`,
    [sessionId, type],
  )
  return row ? Number(row.count) : 0
}

/**
 * The newest event id in a session, or null if it has none.
 *
 * A poll cursor. `null` means "no events yet", which is a real state on a
 * session that has just started and must not be confused with error.
 */
export async function latestEventId(
  sessionId: string,
  executor: Db = db,
): Promise<string | null> {
  const row = await executor.queryOne<{ id: string }>(
    `SELECT id::text AS id
       FROM session_events
      WHERE session_id = $1
      ORDER BY id DESC
      LIMIT 1`,
    [sessionId],
  )
  return row?.id ?? null
}
